# Generated by Django 3.0.6 on 2020-09-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_addnewquizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewquizquestion',
            name='quizcode',
            field=models.CharField(max_length=30),
        ),
    ]
