# Generated by Django 3.0.6 on 2020-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200908_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewquizquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='addnewquizquestion',
            name='option1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='addnewquizquestion',
            name='option2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='addnewquizquestion',
            name='option3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='addnewquizquestion',
            name='option4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='addnewquizquestion',
            name='question',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
